version: "3.8"
services:
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: notesadmin
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: notesapi
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
  #     - db:/var/lib/postgresql/data

  test-app:
    build:
      context: .
    # depends_on:
    #   - postgres
    ports:
      - '3000:3000'
    environment:
      # DB_HOST: postgres
      PORT: 3000
    volumes:
      # - ./notes:/opt/test-app/notes
      - ./public:/opt/test-app/public
      - ./scripts:/opt/test-app/scripts
      - ./server:/opt/test-app/server
      - ./src:/opt/test-app/src
      # - ./credentials.js:/opt/test-app/credentials.js

# volumes:
#   db:
